# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: artahack.io
url: 'http://artahack.io'
author:
  name: Andrew McWilliams
  email: andy@jahya.net

display-call-banner: true
call-url: /winter-2018/call
call-text: Apply now for the 2018 Open Call

# Grunt handles images and assets.
exclude: ['images', 'stylesheets', 'javascript', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
excerpt_separator: <!--excerpt-ends-->

permalink: /blog/:title/
paginate: 7
paginate_path: "/blog/page:num/"

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

slider_array: []

highlighter: true

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

collections:
  alumni:
    output: false
    permalink: /alumni/:title/
  projects:
    output: true
    permalink: /projects/:title/