# Site settings
title: Art-A-Hack
email: art-a-hack@jahya.net
description: "Art-A-Hack is about bringing artists, engineers and technology researchers together, to make something new"
baseurl: ""
url: "http://art-a-hack.github.io"

# Build settings
markdown: kramdown
permalink: /posts/:year/:month/:day/:title
