name: artahack.io
url: 'https://artahack.io'
author:
  name: Art-A-Hack
  email: info@artahack.io

display-banner: false
banner-url: /summer-2021/call/
banner-text: Apply now for Art-A-Hack&trade; 2021

include: ['.htaccess']

excerpt_separator: <!--excerpt-ends-->

permalink: /blog/:title/
paginate: 7
paginate_path: "/blog/page:num/"

sass:
  sass_dir: style
  style: compressed

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

collections:
  alumni:
    output: false
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      type: pages
    values:
      layout    : default
  - scope:
      type: posts
    values:
      layout    : post
      bodyid    : blog
      bodyclass : post
  - scope:
      type: projects
    values:
      layout    : project
      bodyid    : projects
      bodyclass : post