name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - source-jekyll

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          target_branch: gh-pages